networks:
  sermas_dev:
    external: true

services:
  speechbrain:
    image: sermas/speechbrain
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/models:/app/speechbrain_models
      - ./data/cache/torch:/root/.cache/torch
      - ./data/cache/huggingface:/root/.cache/huggingface
      - ./data/data/torch:/data
      - ./sermas_speechbrain:/app/sermas_speechbrain
      - ./.env:/app/.env
    networks:
      - sermas_dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
