networks:
  sermas_dev:
    external: true

services:
  speechbrain:
    image: sermas/speechbrain
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/models:/app/speechbrain_models
      - ./data/cache/torch:/root/.cache/torch
      - ./data/cache/huggingface:/root/.cache/huggingface
      - ./data/data/torch:/data
      - ./sermas_speechbrain:/app/sermas_speechbrain
    networks:
      - sermas_dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speechbrain.rule=PathPrefix(`/speechbrain`)"
      - "traefik.http.routers.speechbrain.service=speechbrain@docker"
      - "traefik.http.services.speechbrain.loadbalancer.server.port=5011"
      - "traefik.http.routers.speechbrain.middlewares=speechbrain"
      - "traefik.http.middlewares.speechbrain.stripprefix.prefixes=/speechbrain"
      - "traefik.http.middlewares.speechbrain.stripprefix.forceslash=false"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
